# Generated by Django 6.0 on 2025-12-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_path', models.CharField(max_length=512)),
                ('dataset_type', models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('validation', 'Validation')], db_index=True, default='train', max_length=10)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('source_dataset', models.CharField(default='hagrid', max_length=100)),
            ],
            options={
                'db_table': 'image_metadata',
                'indexes': [models.Index(fields=['label', 'dataset_type'], name='image_metad_label_2cb4b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_file', models.CharField(max_length=255)),
                ('framework', models.CharField(default='tensorflow', max_length=50)),
                ('training_date', models.DateTimeField()),
                ('training_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('train_dataset_size', models.IntegerField()),
                ('test_dataset_size', models.IntegerField(blank=True, null=True)),
                ('validation_dataset_size', models.IntegerField(blank=True, null=True)),
                ('epochs', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('learning_rate', models.FloatField(blank=True, null=True)),
                ('image_size', models.IntegerField()),
                ('train_accuracy', models.FloatField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('test_accuracy', models.FloatField()),
                ('train_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('test_loss', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('deployment_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_models', to=settings.AUTH_USER_MODEL)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('final_metrics', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('model_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_run', to='core.modelversion')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
