# Generated by Django 6.0 on 2025-12-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_path', models.CharField(max_length=512)),
                ('dataset_type', models.CharField(choices=[('train', 'Training'), ('test', 'Test'), ('validation', 'Validation')], db_index=True, default='train', max_length=10)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('source_dataset', models.CharField(default='hagrid', max_length=100)),
            ],
            options={
                'db_table': 'image_metadata',
                'indexes': [models.Index(fields=['label', 'dataset_type'], name='image_metad_label_2cb4b8_idx')],
            },
        ),
    ]
