# Generated by Django 6.0 on 2025-12-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadtask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagemetadata',
            name='image_metad_label_2cb4b8_idx',
        ),
        migrations.DeleteModel(
            name='ImageMetadata',
        ),
        migrations.RemoveField(
            model_name='modelversion',
            name='image_size',
        ),
    ]
