# Generated by Django 6.0 on 2025-12-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_imagemetadata_image_metad_label_2cb4b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='confusion_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='test_f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='test_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='test_recall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
