# Generated by Django 6.0 on 2026-01-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelversion_confusion_matrix_and_more'),
        ('core', '0006_dataset_label_stats'),
    ]

    operations = [
    ]
