# Generated by Django 6.0 on 2026-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_prediction_predictions_session_415960_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='class_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
